parameters:
        hwi_oauth.authentication.provider.oauth.class: Dashboard\CommonBundle\Security\Core\User\OAuthProvider
services:
    my_project.oauth.user_provider:
        class: Dashboard\CommonBundle\Security\Core\User\OAuthUserProvider
        arguments: [ @doctrine.orm.entity_manager, @security.encoder_factory ]
    app.helpers:
        class: Dashboard\AdminBundle\Helpers
    app.simpleimage:
        class: Dashboard\AdminBundle\SimpleImage
    dashboard_user.login_listener:
      class: Dashboard\CommonBundle\Listener\LoginListener
      arguments: ['@security.context', '@session']
      tags:
          - { name: kernel.event_listener, event: security.interactive_login }
    dashboard_session.session_listener:
      class: Dashboard\CommonBundle\Listener\SessionListener
      arguments: ['@session']
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }